product_listing_site/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls', namespace='store')),
    # Redirects root to /store/
    re_path(
        r'^$', RedirectView.as_view(url='/store/', permanent=True)
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import (
    CategoryListView,
    ProductListView,
    ProductDetailView,
    ReportView,
    PurchaseView,
    PurchaseSuccessView,
    HomeView,
    register,
)
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'store'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('register/', register, name='register'),
    path('login/', LoginView.as_view(template_name='store/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('categories/<str:category>/', ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('report/', ReportView.as_view(), name='report_view'),
    path('purchase/', PurchaseView.as_view(), name='purchase_view'),
    path('purchase/success/', PurchaseSuccessView.as_view(), name='purchase_success'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User


class ProductCategory(models.Model):
    title = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.title


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    image = models.ImageField(upload_to='product_images/')
    average_rating = models.FloatField()
    rating_count = models.IntegerField()

    def __str__(self) -> str:
        return self.title


class Purchase(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ManyToManyField(Product, through='PurchaseProduct')
    purchase_date = models.DateTimeField()

    def __str__(self) -> str:
        return f'{self.user.username} - {self.purchase_date}'


class PurchaseProduct(models.Model):
    purchase = models.ForeignKey(Purchase, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self) -> str:
        return f'{self.purchase} - {self.product.title} x {self.quantity}'

store/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from .models import Product, PurchaseProduct


class PurchaseForm(forms.ModelForm):
    class Meta:
        model = PurchaseProduct
        fields = ['product', 'quantity']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['product'].queryset = Product.objects.all()
        self.fields['product'].empty_label = 'Select a Product'
        self.fields['product'].widget.attrs.update({'class': 'form-control'})
        self.fields['quantity'].widget.attrs.update({'class': 'form-control'})
        self.fields['quantity'].initial = 1
        self.fields['quantity'].min_value = 1

    def clean_quantity(self):
        """
        Custom validation for the 'quantity' field.
        Ensures that the quantity is at least 1.
        """
        quantity = self.cleaned_data.get('quantity')
        if quantity < 1:
            raise ValidationError("Quantity must be at least 1.")
        return quantity


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

store/views.py
from django.views.generic import ListView, DetailView, TemplateView
from django.views import View
from django.shortcuts import render, redirect
from .forms import PurchaseForm, UserRegisterForm
from .models import ProductCategory, Product, Purchase, PurchaseProduct
from django.db.models import Sum
from django.utils.dateparse import parse_date
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.contrib.auth import login
from django.utils import timezone
from django.utils.dateparse import parse_datetime


class CategoryListView(ListView):
    model = ProductCategory
    template_name = 'store/category_list.html'


class ProductListView(ListView):
    model = Product
    template_name = 'store/product_list.html'

    def get_queryset(self):
        return Product.objects.filter(category__title=self.kwargs['category'])


class ProductDetailView(DetailView):
    model = Product
    template_name = 'store/product_detail.html'


class ReportView(LoginRequiredMixin, UserPassesTestMixin, View):
    def test_func(self):
        # Determine whether the user is staff
        return self.request.user.is_staff

    def get(self, request):
        products = Product.objects.all()
        return render(request, 'store/report.html', {'products': products})

    def post(self, request):
        selected_product_id = request.POST.get('product')
        start_date_str = request.POST.get('start_date') + " 00:00:00"
        end_date_str = request.POST.get('end_date') + " 23:59:59"

        # Convert to timezone-aware datetime objects
        start_date = timezone.make_aware(parse_datetime(start_date_str))
        end_date = timezone.make_aware(parse_datetime(end_date_str))

        purchases = PurchaseProduct.objects.filter(
            product_id=selected_product_id,
            purchase__purchase_date__range=[start_date, end_date],
        )
        total_revenue = sum(
            purchase.product.price * purchase.quantity for purchase in purchases
        )
        product = Product.objects.get(id=selected_product_id)

        return render(
            request,
            'store/report.html',
            {
                'total_revenue': total_revenue,
                'product': product,
                'purchases': purchases,
                'products': Product.objects.all(),
            },
        )


class PurchaseView(LoginRequiredMixin, View):
    def get(self, request):
        form = PurchaseForm()
        return render(request, 'store/purchase.html', {'form': form})

    def post(self, request):
        form = PurchaseForm(request.POST)
        if form.is_valid():
            purchase = Purchase.objects.create(
                user=request.user, purchase_date=timezone.now()
            )
            PurchaseProduct.objects.create(
                purchase=purchase,
                product=form.cleaned_data['product'],
                quantity=form.cleaned_data['quantity'],
            )
            return redirect('store:purchase_success')
        else:
            # If form is not valid, re-render the page with form errors
            return render(request, 'store/purchase.html', {'form': form})


class PurchaseSuccessView(TemplateView):
    template_name = 'store/purchase_success.html'


class HomeView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'store/home.html')


def register(request):
    """Function-based view for User registration"""
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            login(request, user)  # Log the user in after registering
            return redirect('store:home')
    else:
        form = UserRegisterForm()

    return render(request, 'store/register.html', {'form': form})

store/templates/store/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>{% block title %}Online Store{% endblock %}</title>
		{% load static %} {# Bootstrap CSS #}
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
			crossorigin="anonymous"
		/>

		{# Font Awesome CSS #}
		<link
			href="{% static 'fontawesomefree/css/all.min.css' %}"
			rel="stylesheet"
			type="text/css"
		/>

		{# Custom CSS #}
		<link rel="stylesheet" href="{% static 'store/style.css' %}" />
	</head>
	<body class="d-flex flex-column" style="min-height: 100vh;">
		<header>
			<nav
				class="navbar navbar-expand-lg bg-body-tertiary bg-dark border-bottom border-body fixed-top"
				data-bs-theme="dark"
			>
				<div class="container-fluid">
					<a class="navbar-brand" href="{% url 'store:home' %}">
						<i class="fa-solid fa-shop"></i>
					</a>
					<button
						class="navbar-toggler"
						type="button"
						data-bs-toggle="collapse"
						data-bs-target="#navbarSupportedContent"
						aria-controls="navbarSupportedContent"
						aria-expanded="false"
						aria-label="Toggle navigation"
					>
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarSupportedContent">
						<ul class="navbar-nav me-auto mb-2 mb-lg-0">
							<li class="nav-item">
								<a class="nav-link" href="{% url 'store:category_list' %}"
									>Products</a
								>
							</li>
							{% if user.is_authenticated and user.is_staff %}
							<li class="nav-item">
								<a class="nav-link" href="{% url 'store:report_view' %}"
									>Report</a
								>
							</li>
							{% endif %}
							{% if user.is_authenticated %}
							<li class="nav-item">
								<a class="nav-link" href="{% url 'store:purchase_view' %}"
									>Purchase</a
								>
							</li>
							{% endif %}
						</ul>
						<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
							{% if user.is_authenticated %}
							<li class="nav-item">
								<a class="nav-link" href="{% url 'store:logout' %}">Logout</a>
							</li>
							{% else %}
							<li class="nav-item">
								<a class="nav-link" href="{% url 'store:register' %}">
									Sign-up
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{% url 'store:login' %}">Login</a>
							</li>
							{% endif %}
						</ul>
					</div>
				</div>
			</nav>
		</header>

		<main class="flex-grow-1 pb-4"> {# Content grows to fill available space #}
			{% block content %}
			{# content will be overridden in child templates #}
			{% endblock %}
		</main>

		<footer class="mt-auto bg-dark text-white"> {# Footer sticks to the bottom #}
			<div class="container-fluid py-3">
				<!-- Footer Content Here -->
				<div class="row">
					<div class="col-md-6">
						<h5>About Online Store</h5>
						<p>Online Store offers a wide range of products and services. Find what you need with great deals!</p>
					</div>
					<div class="col-md-3">
						<h5>Quick Links</h5>
						<ul class="list-unstyled">
							<li><a href="{% url 'store:category_list' %}" class="text-white">Products</a></li>
							{% if user.is_authenticated and user.is_staff %}
							<li><a href="{% url 'store:report_view' %}" class="text-white">Report</a></li>
							{% endif %}
							{% if user.is_authenticated %}
							<li><a href="{% url 'store:purchase_view' %}" class="text-white">Purchase</a></li>
							{% endif %}
						</ul>
					</div>
					<div class="col-md-3">
						<h5>Follow Us</h5>
						<a href="https://www.facebook.com" class="text-white me-2"><i class="fab fa-facebook-f"></i></a>
						<a href="https://www.twitter.com" class="text-white me-2"><i class="fab fa-twitter"></i></a>
						<a href="https://www.instagram.com" class="text-white"><i class="fab fa-instagram"></i></a>
					</div>
				</div>
			</div>
			<div class="text-center py-3" style="background-color: rgba(0, 0, 0, 0.2);">
				© 2023 Online Store
			</div>
		</footer>

		{# Bootstrap JS, Popper.js #}
		<script
			src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
			integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
			crossorigin="anonymous"
		></script>
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
			crossorigin="anonymous"
		></script>
	</body>
</html>

store/templates/store/category_list.html
{% extends 'base.html' %}

{% block title %}Category List{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Categories</h1>
    <div class="row">
        {% for category in object_list %}
        <div class="col-md-4 mb-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ category.title|title }}</h5>
                    <a href="{% url 'store:product_list' category.title %}" class="btn btn-primary">View Products</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

store/templates/store/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="container-fluid">
        <!-- Hero Section -->
        <div class="p-5 mb-4 bg-light rounded-3 border">
            <div class="container-fluid py-5">
                <h1 class="display-5 fw-bold">Welcome to Our Product Listing Site</h1>
                <p class="col-md-8 fs-4">Explore our wide range of products and find what you need with great deals!</p>
                <a class="btn btn-primary btn-lg" href="{% url 'store:category_list' %}" role="button">View Products</a>
            </div>
        </div>

        <!-- Additional Sections (Optional) -->
        <div class="row align-items-md-stretch">
            <div class="col-md-6">
                <div class="h-100 p-5 text-white bg-dark rounded-3">
                    <h2>Special Offers</h2>
                    <p>Don't miss out on our exclusive deals and discounts on select products.</p>
                    <button class="btn btn-outline-light disabled" type="button">Explore Offers</button>
                </div>
            </div>
            <div class="col-md-6">
                <div class="h-100 p-5 bg-light border rounded-3">
                    <h2>Latest Products</h2>
                    <p>Check out the latest additions to our catalog and stay ahead of the trends.</p>
                    <button class="btn btn-outline-secondary disabled" type="button">New Arrivals</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

store/templates/store/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">Login</h2>
                </div>
                <div class="card-body">
                    <form method="POST" class="needs-validation" novalidate>
                        {% csrf_token %}
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}
                        {% for field in form %}
                            <div class="form-group mb-3 {% if field.errors %}has-error{% endif %}">
                                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                {{ field }}
                                {% for error in field.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary w-100">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

store/templates/store/product_detail.html
{% extends 'base.html' %}

{% block title %}Product Detail{% endblock %}

{% block content %}
<div class="container mt-4">
    <!-- Back Button -->
    <div class="mb-3">
        <a href="{% url 'store:product_list' object.category.title %}" class="btn btn-secondary">Back to Products</a>
    </div>

	<div class="row">
		<div class="col-md-6">
			<img
				src="{{ object.image.url }}"
				alt="{{ object.title }}"
				class="img-fluid img-thumbnail product-img"
			/>
		</div>
		<div class="col-md-6">
			<div class="card">
				<div class="card-body">
					<h1 class="card-title">{{ object.title }}</h1>
					<p class="card-text"><strong>Price:</strong> ${{ object.price }}</p>
					<p class="card-text">
						<strong>Description:</strong> {{ object.description }}
					</p>
					<p class="card-text">
						<strong>Average Rating:</strong> {{ object.average_rating }}
					</p>
					<p class="card-text">
						<strong>Rating Count:</strong> {{ object.rating_count }}
					</p>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

store/templates/store/product_list.html
{% extends 'base.html' %}

{% block title %}Product List{% endblock %}

{% block content %}
<div class="container mt-4">
	<!-- Back Button -->
    <div class="mb-3">
        <a href="{% url 'store:category_list' %}" class="btn btn-secondary">Back to Categories</a>
    </div>

    <h1 class="mb-4">Products</h1>
    <div class="row">
        {% for product in object_list %}
        <div class="col-md-4 mb-3">
            <div class="card h-100">
                <img src="{{ product.image.url }}" class="card-img-top img-thumbnail product-img" alt="{{ product.title }}">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">{{ product.title }}</h5>
                    <p class="card-text">${{ product.price }}</p>
					<div class="mt-auto">
						<a href="{% url 'store:product_detail' product.id %}" class="btn btn-primary">View Details</a>
					</div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

store/templates/store/purchase.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Purchase{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Submit a Purchase</h1>
    <form method="POST" class="needs-validation" novalidate>
        {% csrf_token %}
        {% if form.non_field_errors %}
            <div class="alert alert-danger">
                {{ form.non_field_errors }}
            </div>
        {% endif %}
        {% for field in form %}
            <div class="mb-3">
                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                {{ field|add_class:"form-control" }}
                {% if field.help_text %}
                    <div class="form-text">{{ field.help_text }}</div>
                {% endif %}
                {% for error in field.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                {% endfor %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Submit Purchase</button>
    </form>
</div>
{% endblock %}

store/templates/store/purchase_success.html
{% extends 'base.html' %}

{% block title %}Purchase Success{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card text-center">
                <div class="card-header">
                    <h2>Purchase Successful</h2>
                </div>
                <div class="card-body">
                    <p class="card-text">Your purchase has been successfully submitted.</p>
                    <a href="{% url 'store:home' %}" class="btn btn-primary">Return to Home</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

store/templates/store/register.html
{% extends 'base.html' %}

{% block title %}Sign-up{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">Sign-up</h2>
                </div>
                <div class="card-body">
                    <form method="POST" class="needs-validation" novalidate>
                        {% csrf_token %}
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}
                        {% for field in form %}
                            <div class="form-group mb-3 {% if field.errors %}has-error{% endif %}">
                                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                {{ field }}
                                {% for error in field.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary w-100">Sign-up</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

store/templates/store/report.html
{% extends 'base.html' %}

{% block title %}Report{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Product Sales Report</h1>

    <form method="post" class="mb-4">
        {% csrf_token %}
        <div class="row g-3">
            <div class="col-md-4">
                <label for="product" class="form-label">Select Product:</label>
                <select name="product" id="product" class="form-select">
                    {% for product in products %}
                    <option value="{{ product.id }}">{{ product.title }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-md-4">
                <label for="start_date" class="form-label">Start Date:</label>
                <input type="date" name="start_date" id="start_date" class="form-control" required />
            </div>

            <div class="col-md-4">
                <label for="end_date" class="form-label">End Date:</label>
                <input type="date" name="end_date" id="end_date" class="form-control" required />
            </div>
        </div>

        <button type="submit" class="btn btn-primary mt-3">Generate Report</button>
    </form>

    {% if total_revenue %}
    <div class="report-results">
        <h2>Report for {{ product.title }}</h2>
        <p>Total Revenue: ${{ total_revenue|floatformat:2 }}</p>

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Purchased By</th>
                    <th scope="col">Purchase Date</th>
                </tr>
            </thead>
            <tbody>
                {% for purchase in purchases %}
                <tr>
                    <td>{{ purchase.purchase.user.username }}</td>
                    <td>{{ purchase.purchase.purchase_date }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}
</div>
{% endblock %}